version: "3.5"
services:
  producer:
    image: test-producer-net
    build: producer
    networks:
    - confluent
  consumer:
    image: test-consumer-net
    build: consumer
    networks:
    - confluent

networks:
  confluent: