version: "3.5"
services:
  one:
    image: ubuntu:18.04
    hostname: one
    command: sh -c 'apt-get update && apt-get install -y iperf3 inetutils-ping iproute2 && sleep 3600'
    cap_add:
    - NET_ADMIN
    networks:
    - kafka-net

  two:
    image: ubuntu:18.04
    hostname: two
    command: sh -c 'apt-get update && apt-get install -y iperf3 inetutils-ping iproute2 && sleep 3600'
    cap_add:
    - NET_ADMIN
    networks: 
    - kafka-net

networks:
  kafka-net: