version: "3.5"
services:
  producer:
    image: test-producer-net
    build: producer
    networks:
    - app-net
  consumer:
    image: test-consumer-net
    build: consumer
    networks:
    - app-net

networks:
  app-net: