global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'zk1'
    static_configs:
      - targets: ['zk1:7071']
  - job_name: 'zk2'
    static_configs:
      - targets: ['zk2:7071']
  - job_name: 'zk3'
    static_configs:
      - targets: ['zk3:7071']
  - job_name: 'kafka1'
    static_configs:
      - targets: ['kafka1:7071']
  - job_name: 'kafka2'
    static_configs:
      - targets: ['kafka2:7071']
  - job_name: 'kafka3'
    static_configs:
      - targets: ['kafka3:7071']
