version: "3.5"
services:
  producer:
    image: jmx-producer
    build: producer
    networks:
      - app-net
    ports:
      - 4444:4444
  consumer:
    image: jmx-consumer
    build: consumer
    networks:
      - app-net
    ports:
      - 4445:4445

networks:
  app-net: