version: "3.5"
services:
  producer:
    image: cnfltraining/jmx-producer:1.0
    build: producer
    networks:
      - app-net
    ports:
      - 4444:4444
  consumer:
    image: cnfltraining/jmx-consumer:1.0
    build: consumer
    networks:
      - app-net
    ports:
      - 4445:4445

networks:
  app-net: