version: "3.5"
services:
  producer:
    image: cnfltraining/test-producer-net:1.0
    build: producer
    networks:
    - app-net
  consumer:
    image: cnfltraining/test-consumer-net:1.0
    build: consumer
    networks:
    - app-net

networks:
  app-net: